[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b934ca7f326350c2a35da6f0e105ab40c2c6907"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "7564b897047ed37f95d8dafa1109a46851188cd822673c48739df0d1ddfadd4b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e17eeb3b7331c71e1df3ae9308329acd1c25d71"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "c532560d2e1892ba5ebb8c8392b2642d519dbd4c4f669b31a5b1b4f89bc43777"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45055d90beb612fcff6920b4d67145a607c99aca"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "ed0113954e87e6335ace16ee5d4a80768538b6a1f19594db6d4bd1b69bd3b7f2"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ff0de8d8392c7e89f8bf330018df0e5ba28d4f6"
os = "windows"

    [[Osi.download]]
    sha256 = "70c1ad0563ac300ec0cbd3c1b3420bd07d33cf06d124d746b2e349b0f0f53769"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2b554fd316671a594ebab95f7c6861e7759fdea"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "21ddd9a2e31609b126439e2dbdf2e85b29ed233f095322958fec8c562f2a1cca"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2d7e0e623fa62a0c52e39098cbcfd482f68212d"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "96855a8175373605401915a8b163fbe97300de1337b006e3284d31b0559480bf"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3fd7a08947fd0711f323c4f08a0df7e44ee7537"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "495a529761f2dfa8d494901dda3a1cf575d12a381cf3824a11bcf07a58646d56"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f09070c01b41f4001ef61eac3106551753aec9c"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "84dd3e580b4a68457c0a2f2e1d52f24a3ac96254b2dd69029f1fe3adcbe78ae0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ae2f2c98576214f6f3d8f8ffc5076082ca17b57"
os = "macos"

    [[Osi.download]]
    sha256 = "53da6cf3d2c73f0a2bc7ee4d9855894214a1507be744571d859a610e1ee099a6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e4a9b1de51e245678562c81824290d124b48bb6"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "7123079b46213a355190a89ba2bbc54cea49b9ea4e9a2dc7a749cace07f32ae4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0fc77358e1f190615fd00c8ac7d99c9bdf477ef"
os = "windows"

    [[Osi.download]]
    sha256 = "f3c436822340c0076c61f220669f67c3d32c6420128b6baa059ba70ea6ae4c70"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99163d76c872fc38dd362579082c333656fc8817"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "49003732bc3ad79103ba7c3fdd463b2356d0aedd587a10589943c9e1de591edb"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05ed9f7b4ff8d5aac7dada39f885e22da6bb1176"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "85c97895c3087ab9e70ce91d1bf8ebc974b781909b2cd889482e3ba2c5226129"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ffc5972aba5c63c1273a9c1a4e6d596aee720b85"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "bc9a1ad02fca2b93a7f4229831de7f0917a09ee00cfb934ae849e46975a6f505"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "52cf2c89ae61fcfd84532d3789529a883889caad"
os = "macos"

    [[Osi.download]]
    sha256 = "e0aea3fd07013c8740a48e84bd2d7e9a5bec7755979be27911b085753f68171c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3abe0b3ec870468288df3cbbdba47800e068b14"
os = "windows"

    [[Osi.download]]
    sha256 = "485d349d4631ae90f0d50ce16a2771846f5f81514101b0633abceeec26fc73f0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a40095b5faac7f3a8c576c58f09139b509e91de"
os = "windows"

    [[Osi.download]]
    sha256 = "df32d376da4fb9e69e93cf2b8bf38132437cf2c39e65830539b85e1967c253b3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c32dede43304ffce9e8f151f2d0483a8b7c2e31e"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "1071c0aae46951f98997b7afe735fddb01f3cc95fa096d9f25e4dc6476273e56"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b1cefec5ff4b82a225c123a7da423414df2d86e"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "a179769ac9dff73c8a2b53cc0d56b31034cad9618b3e9fd1ec186061df2b1498"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "394758fb6a2c29b6566de0813721eccc1d6fcfe9"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b22132f3806c28cda7f860de9606a2d3cf821846704cf0605fa3d271faf91231"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9fb2cce34b495df2d6b0ea076955dad2e9caaa9"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "193e5f5c75877843db3b9c8890c9b53f9c5049bfe1fd55a345f3ecaeff200e53"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "154155a8107dd94bbd4cc0a49cd74fad2abc3e7b"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "78231a09e6d77d8ba38519aed44cf1d2c8135bf95b5c546522e1981424a4b58d"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+2/Osi.v0.108.5.i686-linux-musl-cxx03.tar.gz"
