[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e73577435a72a283b16cfaff3e78214f194de7b4"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "76771d7dd494e9799ba1f02a7069696797d10e62de0917ba716f1a282e982f68"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52a731640321bcf99ae65d06d14c53f8b479e57c"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "59b20c2b957a4aa4ef9f6d89f01c363d5cdf24babaf61624be43d8aba5d3b56b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af1b0baf495badab7586bebe1f3703aaa99334c9"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "2165ef9a6683c0beea5d170a37d6cd6fa6d02b9dbe9cdc3b952b85eb061c9c75"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c2f5b78aec561248979219e2eeb322e2179c7c4"
os = "windows"

    [[Osi.download]]
    sha256 = "d5b223072c3ea480a327208f135f947d94f55521317e62d358cd34be443c737a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1103494a1d6b3b28b59f6745da37727b2e2d788f"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "50c389d2882314d50ff6f68d7439a481d50e9f3092905c98f3a467d2b7af39ba"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7fea26549cc614170cacbb544ac7f45b34e97e8"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "ce1ff480d699f6d88f776121ff02d51e468997f863bbfc54cd84b7069afc771a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcd51d2c5ef2096dc64664208195c80b1cbfdafa"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b4826983699176dc103b1f8d230229acdf178c45e6c2805e8c5bd5d204568126"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afd1a9e1ad7926a340f4bb68d3dad517302450c9"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "29c55bc8b12f3b88d59005d3b2edc9256df5ecb10397797a78c74e3543d6026e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c26bc14bd7172d0021cd826f5af8cec25ea9adc"
os = "macos"

    [[Osi.download]]
    sha256 = "d143b7c2ea3c29bb61ee6ea54de2959314483510b962ae957381abafbee6d754"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff5821f88319d1678f87e2679463c8681c5e0e4"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "09a9c5da4e12140c9e10a586834d9e256268bbfaa0132fa8a11169302693505e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd055416c39493880799c56abfdf56a2dc650dc3"
os = "windows"

    [[Osi.download]]
    sha256 = "e6735a397b989fe9ad3a7900112143a6aa551e6f1d2904c4128e0b10ca4e6214"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc4bd7fcecb89a3b6cecc27c7b641ed43273945f"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "1f674c9d2e035e868e0b5e51a4b2f686bf7bfc620a4877d817aa8a97f946bf02"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "766a6d72ad66e14e88f580c33e7d7dad5e22dbb2"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "94b9c5704b6be3e4c3b9b0572cc428dea219e277719af4e6b02e661245f4e689"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5107f1c91d76d6a60510c02a37330ce914e9a52e"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "de7a3cc2060fea42eb2aa2c4c94c768cff47cbbf607727fb846b5318d8287a8c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee4ad262f983c2ac202f2f1c82c36da3f1327d7d"
os = "macos"

    [[Osi.download]]
    sha256 = "edf64a5a1c1184e0ec2b889ea7960b1030dffb0fb524ec0e2952d83b142ba9a5"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b358c90c826392063416129f1e758a7ac778cb1"
os = "windows"

    [[Osi.download]]
    sha256 = "6b7bcfc98f4871c711780052e76e3116cda80c614bb6d27f4e14485e94364a35"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24cd7fea6958852d07a3cef24d07e3837626fa07"
os = "windows"

    [[Osi.download]]
    sha256 = "c054403623964d110ee15a9ccd8afa79f86bc592666f4db609cc07053a868a2a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddfb2df8f0c13d8fc0e8b130a2ec83250f701e3a"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "1a0174ad1adf59a0bfaa160ed0fd1d12a65e50d3adef59b99de7634bebe05ffc"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae72da0ffa201900413f97d5bb1b9cfba9dfa5ce"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "bede1e1524cb9052857b4a68cf26e4c82c3f755c9134af887e2e975bd9658858"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afd30356297766c2a3e93d19fbf99211524634db"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "776ba78894dd4da73095e724dbfba5251acc75d1898cd90428017577f2b05682"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cf40877cca4ed6574d3193843062109c5930f01"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "a3e89402391137ca57751c0555eb218488dd79dcb1a1726de36bcd107ceb76f5"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1c85aec85fc404ac2d171c193b8082f3a44d543"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "e4a5a2ebd3884dd81ed351ddb9ce2a5ed8930ea65907e017b5f0da823e1c54ec"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+1/Osi.v0.108.5.i686-linux-musl-cxx03.tar.gz"
