[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "602be41d2f816619abb148c4b7a505f5743eaf7c"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "20d7afe8461c5fe517e17d348420a1e896c446c425992212afa8f04c7dc309be"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e44bff8c301ee59333797cffb64c6a364470257"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "e8f308961bb5e217b404ebacbae5090e35726e2e68e36c24cbf8ecebc7e60497"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ece99e0d9d2ffa3c3e1c39f89f420f6781d4a71"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "a076a15f25427036f42140dd240db52cf7f28702c741a62d685dcf30f584dede"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deebf5c3844b1b332838ef233f2decd56ee1a6a3"
os = "windows"

    [[Osi.download]]
    sha256 = "c6316b4f629aafa9e9e2d1569725b067aa6382cc318a46e9cb57cf7269aef1c0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ae25b21e2ac517c4ad4dfd398ceb9cbc5906269"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "d6e3fd9c256078443d0c620e86072f6cbeb3eec145156e7252b22f2e9bbe6288"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3129b4953064e306513dd67684610ad5b934a579"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "e335cd03367cfa2c0295bc8811e3b901b6e75e3cde0866c968bf9576568db1dc"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93fb22c99523e7e03d79c427f929f8d733039a81"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "faf982952d1b1d1561bd8c89576a8b0db16d71904e48f8ed2d100336aa3fcc41"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c5ac2e225da4828cb484f36117bdd2938548a7c"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "989575cd649d8b0f10c6f7d64f5bd3928ecfc30b0a7d421196127b6fc4e7f861"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "33ab7592eb25f07985ac5c5c54e5b1cd2f7ec564"
os = "macos"

    [[Osi.download]]
    sha256 = "6032afabe24eb5c571d3b1433981b85031a23dd8dadcc97bc487cfd4a12fe5ae"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c65fbbe2e673654fcb56c755986b53f9d039cae"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "3c079c493a39c5e24a0bca74414f300a56c89f9dc5f2ab887b21365bde0b3701"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0c933de4814997110d34240fc4542300d06295b5"
os = "windows"

    [[Osi.download]]
    sha256 = "b3082e40ede00ed4b0b2450cb2e3fa9e60f00f44d346b55e77d15ef16d853542"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3274e25a4fb61817efba1a89f61b8a0f88c43904"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "fe5334ce03234ecfe32c6563e0f705a6796522789f639c3fab8f4370aa7ba9b0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c7f5e84e3b50b2286be5d279515865f12284bd"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "1abcf5ff9105efe9af01bdc505c4fec72df7a80551aca674839fc352c6361345"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe81acd1cfdff739beccd22d7c1607dbcb7fcf8f"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "3207280ade1533cff5a06a09e722ecb24ee5bf1536045a94dd9cbf0268e65131"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2ce8542a6443898a3e1c68ad7d6ad24b3bac4dc"
os = "macos"

    [[Osi.download]]
    sha256 = "1b6826542fbba08b398c2c43f903050009c5ca8b1e9ab4f50b27a12cd89f1d87"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3ef5c532cd383dffc4e0933f5044ac90e8ae2af"
os = "windows"

    [[Osi.download]]
    sha256 = "bc0ed2f0e22671c0ac48e906f49a2f9868df70264ba67279274bf93ff9e64032"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7c80184be4e129a17b29a51b7bb41b2387f6403"
os = "windows"

    [[Osi.download]]
    sha256 = "945aed0e97887a7c5937d4b5d1b3ea580b99ad363b14b480bb88343724b1f9df"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52ffaf6d652f88f40a1aad3d4d35efc18bf51871"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "3cf34c910d4bfd7491a74536ba999616903b379480e16ddeab1c81c1037f8677"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d59ffcd0bf15f428ae6f6a5b33fce456a91defd"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "df01c90bba24006a2f9b17c5562a6b52e43127ed5a8ac189238e910fa791d75f"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afe3595f0b507e70e67cae8f9f9c3fded6f6a1b6"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "201f5d4c26d542a043a13c566e8364e1c2c63fa5422e66bf52934844fa326d91"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06531a8af9f30fcdd4a49907919086520239f831"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "f9e4ff1ca031425869fedcbb92a0116daba2f5e4837c4b539d246e631521a1ce"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f35e2195eb2ebe371f11dedfa801933e4bcc222"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "0c91e150c9a2493af68e5c4750d2d4b67a698e4288d142215f67230a98c12a8a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+3/Osi.v0.107.9.i686-linux-musl-cxx03.tar.gz"
