[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dded3fb17a905ed604444d04dc1f9462dbd9c4ae"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "56c799834ce7d357e489a06c030a1b1ab221cc73d5a53617d427cf2f938b168e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3565b5d38a737d8d674242b05a7ff01cae115bb4"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "26e011a805bae0eba7055f7cf0e7c58f64897feadfaffa82b007cc5f84fda15e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3b39783043351ad2414b5a1880f7275a5fc29cc"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "f95e73cf187b4668b26d52b7c4c501a6f8355b5d506c6e605228d1087de1c8d3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23ffd4a632b74bc5725e3f3c332155ed90cbcd3f"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "1a5ae7e591a8d5c49d49ad0056f41503ff84e677e93021f709c96c2bd993c78b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "329e6880c93fef8c35e89b5dbddf2a2611d80b82"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "7a9e015f15a221690196f9991a42b8f443b946e0098f1eea1398453339e9dda3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "260f35ba1de585ee35c42d0773c13d3831a7f2a1"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b13b8325f0a8434fb102ddfad8a233f65982792a15f4dbb2f98e55b3fbb548f3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eae8bc5e65bdff58bf1d3d99c7c3cdcf060066d0"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "fbd1ab655d8b39122e8d1fa7986b081327a12af7a9791b553a4e77d185171147"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f91ca21d8cef35d53d097f71387379710c47e581"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "86114572d2e092825b34e37d631369eee6282e8b3f1fe886149fade0fa6caaf6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50bf0a42ec861f9428512ff87c7257ccf6275c5f"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "a02628ff012a1ca3a95ec85defd5f0dc0b610fcd3b89ea0e4c08c1dd0677dc11"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2440128361c6e581224d3801a16abc56ae3a1202"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "e1d6afb3d9ad633355012586bd00313de1a200e682f442ee9877e7193719356a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44577df7eec8317e73b1da8facfcbc4bcde8006d"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "edf5948b5e19353245d7c54b822421e4c956e5524e790429e276b3249a8017af"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc15bbb56e57b5e05295eda9e4a9325163417a06"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "b6cecc9b3f6b7eb22397474bb1a5702dc88733f8f68ba2eabbc07c01e2795f4b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8180e8a31f6f3af3a1a4e9bfc569ec8f77d74b3b"
os = "windows"

    [[Osi.download]]
    sha256 = "da4c180364258abc512178fcad5e29e529c8bd1955eabcc1f70912601510e73c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "76395ae037871d9e1e8d1c1cb613d2ced784121d"
os = "windows"

    [[Osi.download]]
    sha256 = "548a39736b4ea91eba0ec856263a071c9a950c7d8103ec1386247b54750d32f1"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06eefb4b6b500b11cd47998d72e223f938c89d15"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "d9d7a115f07f77be17871bd2a630144bd653469733655c7c525a856fb392bc87"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8498ea93bbc605ebfb6b17c56c7c3579cfed66e"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "ec529f5aa992af1df25b27ae5a4ebd6b9dea0a16c676fe47fad100cd4cff3cca"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
git-tree-sha1 = "fe39013c0534f091ab744b553119d34d01787bfb"
os = "macos"

    [[Osi.download]]
    sha256 = "0688cca1d603897fcb6fab9f41f2050cf76d8da76cc1909482ff6360b229559b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-apple-darwin.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b45a18f7b7f3e50852ba4a34ce40be13b79b44b8"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "31a857e928341b7cac4379735f521cb9150c79f5abaa87aaa96342382315434a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cab585e7113b19690fba4c7b5133994f9bfe26bd"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "ae58c5bf96605ac97f7be92d3cad16a903e99ef6a5268b446f0fd84c5d3125a7"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e82005cf9480ac3b265bdf2c9e2cf43ce133ebe6"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "c63f953642d4ca64e79b51f64462fbe0245c6f8ead7252ecf18e72196b736f4d"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ce2dd39a2c73879c214d9560fb6d1381f4b5fec"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "5f94ed07d0e108832840e298bf0869dc7861e46c3c8fc2483aaad0b36094460b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f81d6c6515b04f4294c15576ad7a8c727fa8ebcd"
os = "windows"

    [[Osi.download]]
    sha256 = "4ccc7d666975c0f3171a09c97ee6b47bef26a52b3d92f8cd4219bba5a784b164"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6eaba6a1c7b37166688944dc56bbb6b0ffc2d080"
os = "windows"

    [[Osi.download]]
    sha256 = "7aa40d7ca1b16274b00638599d3117943cb472f95661eb956f662549dac9f279"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+4/Osi.v0.108.5.x86_64-w64-mingw32-cxx11.tar.gz"
