[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2dd8e459f02f0900af9bfd4a9900dffe71b2c6bb"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "566e619fa00cc390a3e55fbcd5f5edad462d06c95bfd7dfc040c9455ae03d1b0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfb2057d272a2601ae4aa766df4098a2be404a32"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "d65e610944017877d3bc137d6bba5e2a89320f64d6d5e0949d7ee6fd744179f6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "720fa196003058f65af1d0efdd531437d3523290"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "28d292100129fdd76c41d2e6fd496fb5aee226ce64914e4b4f62f2ed1101913b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aa976a4a6bfde58d22f128e3da8214cb88e81c5"
os = "windows"

    [[Osi.download]]
    sha256 = "3f061100b4529c76afd58d7823de247377683a7985ebe41854b9f47047fb938e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3430fa8762e047c4cb4c18b26b0558ecbc5edc83"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "a0634118921ad6f665600dce5717933ec84dbb059464fb7aefe28806f0944303"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7783e61a2c8526e848ab682184540ee37e7920f"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "810971264602150132c5d164de4bbe09da8fee16bbf46594a3582af0d6ff4813"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6d25080d12b74374c17ee81d83cfe60a33e908c"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "e2419315dc7d822a001773cac5543061d6ba605abab82c41c7910e3b3bd3bb81"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "215712a3dc0781a53bb1d1fd2cb437bdac35dff4"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b7a7921f60de62e915aa87123db82b28dfab12cd5954fa16643a4dd1bdea843f"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c79c36001bdc4bc6a5665d4681f8bd4b3a312243"
os = "macos"

    [[Osi.download]]
    sha256 = "0a6ef82aa75d35b0f08cd7f3613bb62c4feb9288986141f5fda6d9ed9094ebf8"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f0e115b3e748f91bfffaf41fa6837ad77361b76"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "ba7d5d5a64e90dc6d44b473e7c17a574a67bfa646139e9dbc6cd2dd7830a778a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6eae8094e9f7f357d791ce6f33d5336f26dd3bdb"
os = "windows"

    [[Osi.download]]
    sha256 = "af24c8bccd67afc425bd0218a67833b7fc468c1236c4073f0dd6b01c4f1b9af6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3770adddb85b3e783ae38c17e27d432f51e513a2"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "e5b67f64197e169ab8843a58ecbc171b71cab690fe860f9cd81fbf0130d4d7c9"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1dba0adb96e8c3fb37ec0d327824e57156467c5"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "7d202295eb0ad624c6637c792f7d4b4934f66bf7437a853d86cdf259e5d8bcf8"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32444658abdc991ce2832546a03201483504f620"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "54d0405b123b1d466e81358e8da5c2ed5e74fb71761afa9d60f2964d3c01e3db"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "676822d032ce513e27a31fc7dae162992cae11bd"
os = "macos"

    [[Osi.download]]
    sha256 = "bacc47d84129a512a26bd369a14d364a2e013031eb48bdf3244e01807cf79647"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b788b0bee37de8be48fc7dcdac2fd3eed6f74c98"
os = "windows"

    [[Osi.download]]
    sha256 = "e6dcc80557b1edb7149679dbca51f05ec42aefc57750e431921af898f898445b"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd6160260794c3ad348b21b061141baf301eb57e"
os = "windows"

    [[Osi.download]]
    sha256 = "7a93746a4d2d367567ce0203cedfb26029532a9768a464b4c5c6f931864cd713"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7db1643c5b2be0810bf01814d2035fd40dff2534"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "37d05fc374cb963bf8942d182a504e252318a1ae74f4160146f149f26ada3387"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fd74585f80b9a5e891ffdb83f7844f57c8e1459"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "4dbbf8995c4da015b8acb0a06ecc2f3188cdedaf53d043b1c3ced13b4ae3732c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67a5d3f37e29bdfa69434a23bd2cf965cb640d3d"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "5cbb6ac50e007c7928dbf28fbb48587341d0b73d472ecdc5edad25982cf594b0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef2baba851d1a7134fa280d00c2dba2a21375909"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "89b633e27b3d3e2d7becd3756a4c436683935ee41a0115c66a254ba7f80e0183"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3e9c6f1a0ee8cfa523efc3d83bd1fd8adc02c9f"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "fc638a004494456f3e69d7c333d3205486fa42f1cd1d34a0420b0cc4f6320ffe"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+1/Osi.v0.107.9.i686-linux-musl-cxx03.tar.gz"
