[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6208505a3976dd5b30ce1eeca558ca0993fec034"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "b9d177e49f312024c20f8f962157b45f9092487e4a2ae12c3ca44c406901c418"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3240e6dd60e17e9ebc27bf5ed4e420ef4d53de13"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "b8ffe153dfd193566f340aca1bc58eb11026d83f519397187f7830f237dd9dd1"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81ee67006bfed5d5ee1b087db52e62948a113283"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "fc567b1c93ded67a2ef508c874c6f465ff72ab5f8089c23ad390cdf607fae4a0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1168e3a92b1f3e15bbb6fa74966a8f3604541e91"
os = "windows"

    [[Osi.download]]
    sha256 = "51352b44404a9074cfca81a4fde3969090d154659249fc08e253ffb4b9ea7b1d"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "533f433c6247a0b2082476e8a6f82333f792c079"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "72b81e284b4d6acd4ea5ae61caae4473aeced98d02f1f173aecf5fadc95f032e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1003801029986dbc39c5de72df99f51be173527"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "be44701ee8f251ddc4b4149305e5c3f51d248784d4d8eebaf814e2057301085e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "420729816d4902c6580ebdb18fc2d38fc093035e"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "86a5a712c8025524f85dcac28ab6d1f6dfa3c47caa5e794ff7b179327c5186a7"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa40ae30c5a4b2999b913e25f27b1b3821dcc0be"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "6869eb7e7b1602681f01d3a66c3bd6240e94c64141256cb93ffc324ecf973b00"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11f5917ca182539f437a3eaa6bb615e83431f7d6"
os = "macos"

    [[Osi.download]]
    sha256 = "4a1e306b08837a267d818e44030d509885c16b960993538ef5027378c49c745e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c646d3371240e7e5daa59b453b8c5410ef273ec"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "3ef3cc8d69a32c46b7b9c07cca1ea5f579f59f1bfe22fd48fc8824c92a1b4ea4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4f1ceb1d38071e3ebffa135fa8771e81caa69c9"
os = "windows"

    [[Osi.download]]
    sha256 = "50af915d3434a1acbf8b4915a4b153db5cfc054fefe3fc832a5d167a2653ddd4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2b53032588c9edb7fdb579c6279d598cb4a1de2"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "6a4d72a6e0936d32f0ba30a2f1e8238858566d9df8be63d7cde8d1ca37b96aa9"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20f043b4bdafc50a51ef71a8911c1ed1fcc450bb"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "81febe50e197570062af4920fb5cfb0845efcbaca320a10fc92b35bb94b02dd3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f8a6c507b7a9b80a2567ec64a270ff984db1a8a"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "50645c8fc245cad32aa0eda67752417f0ce2853ef3ba1fdfaa869de60f86c0aa"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "550e2d9d762d9d49a295449249a52765416b6def"
os = "macos"

    [[Osi.download]]
    sha256 = "27dc8395e5564989c0caba015e095f43338b4d411c46509fb8a9bcd79c65545c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0fcd18b05de4c9aa1bfa165057ea48e48232586"
os = "windows"

    [[Osi.download]]
    sha256 = "d203f448fc46d53d92af4876eac4f98f3e37ce9e6b0b9bb3d5e67fb9a2fef65a"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32127fcae3ec2203bdc29dccdb06f2709d5d4f4a"
os = "windows"

    [[Osi.download]]
    sha256 = "161a2c81d86b876230c44ccf5446d8127817abb4294eaab32928d415754b28df"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8b7d4d69c1b0483f44f6b02de5c878dc782a1c6"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "b677b748195fccecfc0ac6e00b3b26749d37396010ee78f7e493c5b965d4fd41"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c6c5c9248d9ba786a06cfa4c963e7dbf34961c4"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "de875ee637f381c34360ef630843fe4db388e5fdbb51ceebdc22bad081bc81d4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bfb4488e7cf9ac587ffd7304c403d28ba442cd5"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "f57ff1aadc54209866c08f29e676d9544108f1a53c0825d2a1c12c52ad8dab16"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea069331b80fb288c615461c2f61bd2616545c25"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "dcc6b94878660d59764f80f08680691eb8e43822c723a0ed555dc5b5c39b7821"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a9f8b9a28e23f91de03ee3251e6046c2cbd1c74"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "bfdf679483b21c5cc276e2ddef085a96bd6fa842842c01fc6bbb2850d2e010b6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.5+0/Osi.v0.108.5.i686-linux-musl-cxx03.tar.gz"
