[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ece1726a8c27d8d9a121c7d34470eab88257fa3"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "f274f0a926e5d4eb02682de20ab9e56568e5c661febb720c7565c6935c83b744"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a95538fd418c31978d181e29f312c86eca1da6b"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "c14f976b8667cae40d6b10e003e5320498889be2cefb5989ff40f41455256f02"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9171604b321366c8717f1a877ca63c22ab8c6c6"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "9f742318e8bb876fb77397b23e5d56d73feb39ac111cef831a8631bc7d79ac45"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a126ac21be64caff6801b69486c58229ddbe96d8"
os = "windows"

    [[Osi.download]]
    sha256 = "bbcdaa1d3f961e24cd99b81abdf05726e5ad7f5c0dab72bf1c99c687c26b39b0"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "726b76a322370d77d1263595124854fe7c5020d6"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "0aca69845089dfb0cb40ca7778bed1121201f7719b681a83ecaf3d9ad49266f6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b37538ef6a6f592d69e4d4b17c743e3584ae1438"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "cb5ff8c3aea10eeed2065245dc81597426b9b9a4bf31f94f41dc4880e344bcd1"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc722070e68cabd7af88cdfe31c967090a1fed56"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "79f6096204729663c071f17727daad6bcad017a2e4683433abcae36e5fe5a105"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9dad610c2636b8af26729c50b200291eec37e1e4"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "0e0258223f10250233b6ccbc2d6163127a34530fed502c71f5d1bb61b4b9d560"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6b633b58054fd218ea40ae46edafb755baaa816"
os = "macos"

    [[Osi.download]]
    sha256 = "3031912b5b0604aeddf365ddcc940ad1d15f7181ed84de870599a5ef4907d038"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-apple-darwin14-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c64a080d9dc63cb5506f66fc0f7d22c1cf15770"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "54b7f410768127b1933088aa386e3887798961924b660a8e16e31bd0b14a474e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdec6813170bea74636336e63b9391703cb767bc"
os = "windows"

    [[Osi.download]]
    sha256 = "9aa047e935574cdc4202ac3ec7816ba9cf49c40070a2b3ab5af01e4651d364c1"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f70ce41a316320cb4309c1659374d822b5f3e34a"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b386290ccf3045c030d6a53cebc77bb06c296ecc2efbc22f90238b7f8c125be9"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20ba19d8f1940844e49e634bb5a0a5ca4278b073"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "b1e5ad67b4a56e952c6b32100d2ba42d8cb97886b37fef6519cbc97b72ab36b9"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc1c955f39a14ccd487f488be43dc4d3307681d9"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "4ac3bc9a1f35fcfd232e9dd16180b6aec30b616bb433d446782284dbbfa806cf"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34daaf09fa928bef2f15724a15685070c4caadc8"
os = "macos"

    [[Osi.download]]
    sha256 = "c29161c8acd54a42425398ca2ca4d58e1306a8b849eac053c33a3ef0bb24fdcb"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.x86_64-apple-darwin14-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d455ae96d1c145ff666581453bb3a31eabab257"
os = "windows"

    [[Osi.download]]
    sha256 = "52b05dcf5341e9fb2acf77dce90569e2f477f7784a9167c1e25be911d28c6251"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "351762ee3e08e520bab63aff70a65f3a9328c346"
os = "windows"

    [[Osi.download]]
    sha256 = "41c032779ba52373baefb6e03f65738b8bc26097b29a2cf2c250016213fb14e6"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da2e147f25eb59ffd30602850aa0e4b66a2c0696"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "5590242eb182eec366a7c87dbecc738b99f3e2a24f3c0965ae86048ab2e7bc3c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4219749acd2297de27f32037674fe09039439b44"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "6309c63d91a599fd143a940deadd6cf88d3d7efb7f918c5b2e1995a18e784964"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d51cd7b8a4113ef3921656fc686bc0633d763e1b"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "d70bceb5a22650a2f51f59a765661914707ae8d0269b846620da5b7a93bf17b4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04ab496d892a6a2131296d706eb30d866292769e"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "6de5cd5490217aa19b37b6d10840cd31659e3e62e8763884d1455bdc531c0616"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "271bce43821d4ee1e831e3ccc968140b338bd542"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "f3d6ba5c19c0f96cd04de27f6863bc8ecd3033cd811c3f18a87c8123ac212f18"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.107.9+2/Osi.v0.107.9.i686-linux-musl-cxx03.tar.gz"
