[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4dd33b7d19e531116c5c8f0febdc784aff2c294"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "a3bbedc3ca908f57b73b40a3c139921f21138413ee8be0ae61187b16a8609eb2"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.aarch64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0be93b274570f69caea0fd9bdbd3697c0399098"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "d520db22470ada9d70946657c88c7f9a0036ceb39eda5e46c06f9dba49b65f9c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.aarch64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4cc200d4ce7a04d62a6cfbe483325d4436f928b"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "e6fdf11b29b5b3f3508eb93b686dd7318607e6c0badbc510d78603ffb6b61bd3"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.aarch64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2045dfc3da2e8497f204414b0853d181f4fec7e"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "f050f319e44076f8d62d9d902975e62409cd1c0295c5f80fe898ed817b6607d4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.aarch64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "563cbcc6e8bc3330ce2a3cba567da46cb91e92c3"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "9a512f3eb5ee27038c663d2d54abb405a0b5d4f1c7791c37d3a23cdd0a4676fe"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f6906ed4455e405ef0b62ceb2f69ab168960115"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "a65967e23801063728d3bcb9ed0c520e8ad44934f1f511aade061b70e7571781"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28672852c74b56fab721f7237dd79d4cf41d2b0e"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "297b52712b057317b363c6a6366acbf2b0ad1b22144157aa56a8faa9566bffac"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Osi]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59976c97a72a0ba84aade9ee8af2a779a235d6ab"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "6851b0f923658db5538e428288f61a2822962118f5e642f10d3a89aafab3b43d"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57c364427b72eabcb112ab8dd0794e2d779946c0"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "01caa6db7d9dc4001704b6306a277c249e363ea7a84173b5d5971fee9d6267bd"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0beccc963fbbae63436a7305222d0f52f70d69e1"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "2c39260317c418fe418352dbb43e5a73a04f60ed75dba647f04105db9b40ad86"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "714cad5732cab63860fa89b2a2116c56e73d9e37"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "995dd64a11499cce9f923556587dcba99ef028f1b3bfa1d51a57f1cfbc97782c"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69057e61a64c84efbdf427127e057734379cea50"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "3b85f54ae5b2ad68d0337726a27af18aaed9bd68122bf3a26f28d8f486053769"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c231a67c8508ca4521fb96e2dd3616eee800af3"
os = "windows"

    [[Osi.download]]
    sha256 = "6e0b685dde90b66870f2d241c70190f017c80d6dac2acbf666feba98034b5a9e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e4f39babdc03c78d401810624b7e24beb52e9c9"
os = "windows"

    [[Osi.download]]
    sha256 = "53732d6c2850b5902a1e270ac714fd68ffd2a20f225f4bb396cb971b2698fc24"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.i686-w64-mingw32-cxx11.tar.gz"
[[Osi]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47ae369fccd38880eb36828b430f6f2863ea8e32"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "d46619c71657407936c0dde9c9b64b0552a1b1f146ff694cf4e3579fe1edb0db"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7452f32652ebffc7197251646ea7d911d8d13cf"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "80029104318690e6b62035c51b6091995479c8894cef4c8dd6774183c1f41b28"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
git-tree-sha1 = "1066f74d8d514ab4fc411e80c825c1ad3aafaf5c"
os = "macos"

    [[Osi.download]]
    sha256 = "a34ca6f82e3453df64ffab58a6ecd78016d166440e9a978d38b21dac1d8d95a4"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-apple-darwin.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86053fb22073071c80f7616d4bd5ef22425aa643"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "694e33bc0064e539488d6e44f0acd152264b259a82a4a3ca4dda588a8fcd9e4d"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-linux-gnu-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6583cdd830bf79a4b97f0be209cb6355b9349c3"
libc = "glibc"
os = "linux"

    [[Osi.download]]
    sha256 = "e78ed43413a81548e6bedfd059d7271e676ce9ab1c12174c495eb60c4f5799cc"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-linux-gnu-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5206074cb5d4d0abc787160c9de8afd03c7d1274"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "1f5ef5f8fce6b39fbc68a75eae946cd5e22be0b7af0915dbf05136e279b7c834"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-linux-musl-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51f481d26b6c46b82fb94ce9efee9727e81480c3"
libc = "musl"
os = "linux"

    [[Osi.download]]
    sha256 = "8d5b5715342d5b0a741f15fd92bd7c1e9ec25141d7e8acedb62847051e9c2f1e"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-linux-musl-cxx11.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "707bc30fbd4b8c885714a2b27c27860d2754a5fa"
os = "windows"

    [[Osi.download]]
    sha256 = "23f1f97f131f0a58bc1fa41f3eee3d8ed40216d21cf1b57fad54f91b1f60b0eb"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[Osi]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93dac7eb499e4faff63a03291a24354c163a3004"
os = "windows"

    [[Osi.download]]
    sha256 = "ab5ff18385111790a9976dc718e10106292bc74fa45a05c6fbb53940ed5f4cfe"
    url = "https://github.com/JuliaBinaryWrappers/Osi_jll.jl/releases/download/Osi-v0.108.6+2/Osi.v0.108.6.x86_64-w64-mingw32-cxx11.tar.gz"
